### ISSUE TITLE
linux运行到ngram2vec/pairs2sgns.py报错

### ISSUE THREAD

**Issue by yongzhuo** [zhezhaoa/ngram2vec#15]
后面的也走不了了
Pairs2sgns
Traceback (most recent call last):
  File "ngram2vec/pairs2sgns.py", line 53, in <module>
    main()
  File "ngram2vec/pairs2sgns.py", line 47, in main
    return_code = subprocess.call(command)
  File "/home/anaconda3/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory:'./word2vec/word2vec': './word2vec/word2vec'
Traceback (most recent call last):
  File "ngram2vec/similarity_eval.py", line 71, in <module>
    main()
  File "ngram2vec/similarity_eval.py", line 41, in main
    matrix, vocab, _ = load_dense(args.input_vector_file)
  File "/home/yongzhuo/ngram2vec/ngram2vec/utils/matrix.py", line 23, in load_dense
    with codecs.open(path, "r", "utf-8") as f:
  File "/home/anaconda3/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/wikipedia/word_word/sgns/sgns.input'

**Comment by yongzhuo** [comment]
解决了，不知道怎么回事，在这里断开，单独抽出来训练，又可以了
i@ubuntu:~/yongzhuo/ngram2vec$ memory_size=4
i@ubuntu:~/yongzhuo/ngram2vec$ cpus_num=4
i@ubuntu:~/yongzhuo/ngram2vec$ corpus=wikipedia
i@ubuntu:~/yongzhuo/ngram2vec$ output_path=outputs/${corpus}/word_word
i@ubuntu:~/yongzhuo/ngram2vec$ python ngram2vec/pairs2sgns.py --pairs_file ${output_path}/pairs --input_vocab_file ${output_path}/vocab.input --output_vocab_file ${output_path}/vocab.output --input_vector_file ${output_path}/sgns/sgns.input --output_vector_file ${output_path}/sgns/sgns.output --threads_num ${cpus_num}

**Comment by yongzhuo** [comment]
但是我单独运行这个函数又可以
