### ISSUE TITLE
type error

### ISSUE THREAD

**Issue by chesterkuo** [zhezhaoa/ngram2vec#5]
I'm trying to create uni_bi.sh with Chinese/utf8 word seg file, however always got following error.
any idea ?

==========
Traceback (most recent call last):
  File "ngram2vec/pairs2counts.py", line 109, in <module>
    main()
  File "ngram2vec/pairs2counts.py", line 88, in main
    counts_file.write(str(old[0]) + " " + str(w) + " " + str(old[1][w]) + "\n")
TypeError: write() argument 1 must be unicode, not str

**Comment by zhezhaoa** [comment]
I think the error is related with character encoding difference between python2 and 3. Maybe using python2 could fix the problem?

**Comment by shubhamnagalwade** [comment]
I am trying to run the word2vecf.py file from simplified file but got following error.
Traceback (most recent call last):
  File "corpus2pairs.py", line 4, in <module>
    from corpus2vocab import getNgram
  File "/home/shubham/Inovanttech/W2V/ngram2vec/ngram2vec/simplified/corpus2vocab.py", line 4, in <module>
    from representations.matrix_serializer import save_count_vocabulary
ModuleNotFoundError: No module named 'representations'

**Comment by zhezhaoa** [comment]
I am sorry that I didn't try the codes in simplified file thoroughly. A simple solution is to add the `save_count_vocabulary` function in `representations.matrix_serializer` into corpus2vocab.py file. And then delete the line `from representations.matrix_serializer import save_count_vocabulary`

**Comment by shubhamnagalwade** [comment]
okay. Thank you.
I will do that .
